version: '3.8'

networks:
  record-net:
    driver: bridge

services:
  frontend:
    build: ./client
    container_name: my_local_front
    image: my_front_test:latest
    ports:
      - "4000:80"
  database:
    container_name: my_db
    image: postgres:13-alpine
    networks:
      - record-net
    environment:
      POSTGRES_DB: journal_api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  backend:
    build: ./server
    container_name: my_local_server
    image: my_server_test:latest
    networks:
      - record-net
    ports:
      - "4005:4005"
    environment:
      - RECORD_DB_SERVER_HOST=database
      - RECORD_DB_SERVER_PORT=5432
      - RECORD_DB_USER=root
      - RECORD_DB_PASSWORD=password
      - RECORD_DB_NAME=journal_api
      - RECORD_PORT=8080
    depends_on:
      - database

